In [1]:
Pandas

NameError: name 'Pandas' is not defined

Pandas

In [2]:
import pandas as pd #pd is an alias for pandas

In [3]:
#pd

In [4]:
!pip install pydataset

Collecting pydataset
  Downloading pydataset-0.2.0.tar.gz (15.9 MB)
     ---------------------------------------- 0.0/15.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/15.9 MB ? eta -:--:--
     ------------------- -------------------- 7.6/15.9 MB 37.8 MB/s eta 0:00:01
     --------------------------------------  15.7/15.9 MB 39.2 MB/s eta 0:00:01
     ---------------------------------------- 15.9/15.9 MB 35.3 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pandas in c:\users\khurshid\anaconda3\lib\site-packages (from pydataset) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\khurshid\anaconda3\lib\site-packages (from pandas->pydataset) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\khurshid\anaconda3\lib\site-packages (from pandas->pydataset) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\khurshid\anaconda3\lib\site-packages (from pandas->pydataset) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\khurshid\anaconda3\lib\site-packages (from pandas->pydataset) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\khurshid\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->pydataset) (1.17.0)
Building wheels for collected packages: pydataset
  Building wheel for pydataset (pyproject.toml): started
  Building wheel for pydataset (pyproject.toml): finished with status 'done'
  Created wheel for pydataset: filename=pydataset-0.2.0-py3-none-any.whl size=15939225 sha256=73c7ca0cb958514c14144349d999d36c9f73fc740d8ee3b3b3733d482a4679a6
  Stored in directory: c:\users\khurshid\appdata\local\pip\cache\wheels\49\2a\45\180e1199b8d925b5c43df8f9850dcc2e5dfc94e3e99a55b83e
Successfully built pydataset
Installing collected packages: pydataset
Successfully installed pydataset-0.2.0

In [5]:
#pip install pydataset
from pydataset import data

initiated datasets repo at: C:\Users\KHURSHID\.pydataset/

In [6]:
#pip install pydataset
from pydataset import data

In [7]:
#https://pydataset.readthedocs.io/en/latest/
mtcars = data('mtcars')
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [8]:
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [9]:
mtcars ["mpg"]

Mazda RX4              21.0
Mazda RX4 Wag          21.0
Datsun 710             22.8
Hornet 4 Drive         21.4
Hornet Sportabout      18.7
Valiant                18.1
Duster 360             14.3
Merc 240D              24.4
Merc 230               22.8
Merc 280               19.2
Merc 280C              17.8
Merc 450SE             16.4
Merc 450SL             17.3
Merc 450SLC            15.2
Cadillac Fleetwood     10.4
Lincoln Continental    10.4
Chrysler Imperial      14.7
Fiat 128               32.4
Honda Civic            30.4
Toyota Corolla         33.9
Toyota Corona          21.5
Dodge Challenger       15.5
AMC Javelin            15.2
Camaro Z28             13.3
Pontiac Firebird       19.2
Fiat X1-9              27.3
Porsche 914-2          26.0
Lotus Europa           30.4
Ford Pantera L         15.8
Ferrari Dino           19.7
Maserati Bora          15.0
Volvo 142E             21.4
Name: mpg, dtype: float64

mtcars[mtcars["hp"] > 150]

mtcars.sort_values(by="mpg" , ascending=False)

In [10]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

mtcars[mtcars["hp"]>150]

In [11]:
result=mtcars[mtcars["hp"] > 150]
print(result)

                      mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   0   1     5
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5

                     carb
Hornet Sportabout       2
Duster 360              4
Merc 450SE              3
Merc 450SL              3
Merc 450SLC             3
Cadillac Fleetwood      4
Lincoln Continental     4
Chrysler Imperial       4
Camaro Z28              4
Pontiac Firebird        2
Ford Pantera L          4
Ferrari Dino            6
Maserati Bora           8